name: CI
on:
  push:
    branches: [ "**" ]
    
jobs:
  ci:
    name: ''
    uses: sjexpos/ecomm-cicd-actions/.github/workflows/app-ci.yaml@main
    secrets: inherit
    with:
      sonar_project_key: orders-service
      sonar_project_name: Orders Service
      docker_images: "['sjexposecomm/orders-service']"
      files_as_artifacts: "['./api/target/orders-service-api','./sdk/target/orders-service-sdk']"

